### ISSUE TITLE
Tweet Download 

### ISSUE THREAD

**Issue by komals1** [tgbot-collection/TeleTweet#10]
Hi again,
Here i won't take much of your time, but do Regards you for a great bot at first,
And then i there is something

I was downloading a video from twitter i find a minor bug that bot can download video from "https" address link but not from "http", this is little bug, okay just want to let you know also.
Examples

Working - https://twitter.com/LakhanMeenaINC/status/1375363254097088516?s=19

Not working - http://twitter.com/LakhanMeenaINC/status/1375363254097088516?s=19

And since i am writing about this, i want to ask if photos can also be download by same way, that'll be great, but completely upto you, Once Again Thank you for your support and great service.

**Comment by BennyThink** [comment]
You should use https instead of http. 

Photos are not supported. Only GIFs and videos are supported.

**Comment by BennyThink** [comment]
fixed and deployed.

**Comment by komals1** [comment]
Thanks.
And thanks for info too.
