### ISSUE TITLE
Multiline posts are split into multiple tweets in a thread

### ISSUE THREAD

**Issue by wisdomtooth** [tgbot-collection/TeleTweet#11]
Like this...
![image](https://user-images.githubusercontent.com/523901/112706012-2b502c80-8eed-11eb-8d7f-e4a976fa3647.png)
... becomes that:
![image](https://user-images.githubusercontent.com/523901/112706047-62bed900-8eed-11eb-895b-fe239fa9f664.png)

Is this intentional? Could we just have it truncated?

**Comment by BennyThink** [comment]
This is intentional. An enter will split you tweet into threads

**Comment by wisdomtooth** [comment]
[This](https://twitter.com/andre__levy/status/1379336108341874695?s=19) is so much better! Thanks for changing it.
![IMG_20210407_001820.jpg](https://user-images.githubusercontent.com/523901/113725581-cab7bf80-9736-11eb-9f38-6b0ae3072210.jpg)
