### ISSUE TITLE
Invalid response, status 401, {"errors":[{"code":32,"message":"Could not authenticate you."}]}

### ISSUE THREAD

**Issue by wisdomtooth** [tgbot-collection/TeleTweet#12]
Haven't seen this before. What might it be?

**Comment by BennyThink** [comment]
Are you using your own infrastructure or my bot?

**Comment by wisdomtooth** [comment]
Yours. It happens right after I click `Let's Begin` regardless of whether I'm logged into Twitter or not. I tried it on Opera, Brave and Firefox, to no avail. The issue seems to be on your host's end. [Here](https://stackoverflow.com/a/24694955/553579) it says there's something to do with the machine's clock.

**Comment by BennyThink** [comment]
Seems like an issue on my end.

**Comment by BennyThink** [comment]
Misconfigure on my side. It should works now.

**Comment by wisdomtooth** [comment]
Working now.
