### ISSUE TITLE
Invalid reponse , status 403. Application can not perform write actions on Trying to Use link to sign in

### ISSUE THREAD

**Issue by swapnill93** [tgbot-collection/TeleTweet#13]
![teletweet2](https://user-images.githubusercontent.com/31537880/120115811-2173cf80-c1a3-11eb-8685-40c7edf96995.jpeg)
We had successfully used TeleTweet Bot with our telegram ID.
But after some time it started giving error code 261 upon trying to tweet.
I stopped the bot and started and signed in again.
But I was not able to sign in using the link . I got the error code status 403. Application can not perform write actions.
Kindly help us urgently . We nneeded it up and runnig for our campaign within few hours.
thanks
![teletweet1](https://user-images.githubusercontent.com/31537880/120115800-1620a400-c1a3-11eb-83c6-eca3f1fa2347.jpeg)

**Comment by BennyThink** [comment]
Let me perform a quick check and get back to you ASAP

**Comment by BennyThink** [comment]
It seems there are something wrong with my developer account. 
I'll try to contact twitter support.

![image](https://user-images.githubusercontent.com/14024832/120158729-06e33a00-c227-11eb-80eb-d88afd413c4d.png)

**Comment by swapnill93** [comment]
Thanks for the information.
Do keep me posted
Dr Swapnil B.

**Comment by BennyThink** [comment]
There were no emails from twitter dev - neither this detail email nor support ticket email. I'll wait

**Comment by swapnill93** [comment]
Is there any way I can get this app up and running from here considering
its open source.
Although I am a doctor by profession I know some Java and C++.  Not well
versed with python.
If I can find time I would try it.

**Comment by swapnill93** [comment]
If you have a telegram account we can discuss the issue there as it
develops.
My username: GreyAlien14

Thanks

**Comment by BennyThink** [comment]
Yes you can. You'll have to do the following things:
1. apply twitter developer, create your own application, you'll need to copy `CONSUMER_KEY`, `CONSUMER_SECRET`
2. install python3 on your own machine(or a server, etc)
3. create telegram bot by talking to @botfather
4. follow this doc https://github.com/tgbot-collection/TeleTweet#general-deployment


You can find my telegram here https://t.me/BennyThink

**Comment by BennyThink** [comment]
I'm taking down this application. Please refer to README.md for more information.

Thank you for your support!
