### ISSUE TITLE
docker compose deploy error : no such file or directory : auth.json 

### ISSUE THREAD

**Issue by kang000feng** [tgbot-collection/TeleTweet#17]
dear developer,
thanks for your great work.  may i ask how to fix the error below?  no such file or directory : auth.json  
and as pic2 shown the py service is only listen on 127.0.0.1 , even though i had set callback url in teletweet.env to my container ip address, so i think this is the problem. 
 
thanks for your help again. 

pic1

![image](https://github.com/tgbot-collection/TeleTweet/assets/9069317/5742965c-1aec-45af-8a71-d55943a3e597)

pic 2
![image](https://github.com/tgbot-collection/TeleTweet/assets/9069317/3210cf55-c091-425c-b036-eb15a4c2c848)

**Comment by kang000feng** [comment]
<img width="945" alt="image" src="https://github.com/tgbot-collection/TeleTweet/assets/9069317/35fbb899-4e93-4bfb-bc90-203230d78fd5">

**Comment by BennyThink** [comment]
updated readme https://github.com/tgbot-collection/TeleTweet#docker

**Comment by kang000feng** [comment]
Can anyone help me here ? i have used the latest docker image and compose file and I’m stuck on below screenshot for several days. Would hugely appreciate it.  

Help !!! 🙏🏼🙏🏼
![image](https://github.com/tgbot-collection/TeleTweet/assets/9069317/78c6532a-aab6-4181-81c9-63abc382a4a8)
