### ISSUE TITLE
Error: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only

### ISSUE THREAD

**Issue by kang000feng** [tgbot-collection/TeleTweet#18]
hello ,

Good day. did anyone have Same issue and get a solution? Does this mean that api V1.1 no longer works?   

![94804E83-718C-4086-821C-F7ADA87AF1B4](https://github.com/tgbot-collection/TeleTweet/assets/9069317/eb80e4ad-d143-4a5d-8c70-77929a2ba1a3)

any insight would be appreciate！

❌ Error: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', 'code': 453}]

**Comment by BennyThink** [comment]
I don't have v2 apps. Won't fix.

**Comment by kang000feng** [comment]
> I don't have v2 apps. Won't fix.

thank you Benny . i understand and appreciate your contribution, may i ask is there any way to create v1 app at the comment? 
and i raised this in case other ppl may have same issue .  
regards.

**Comment by BennyThink** [comment]
Twitter v2 App is now supported.

**Comment by kang000feng** [comment]
> Twitter v2 App is now supported.

thanks very much. may i ask why the bot cann't download video ? my v2 app has Free access,  twitter blocks free users from downloading videos?

**Comment by BennyThink** [comment]
Free plan can only have three endpoints, there's no way to get tweet.

![6192466500456134631_121](https://github.com/tgbot-collection/TeleTweet/assets/14024832/2cb94331-fbf6-4aa0-b637-4fbc8fc8afa1)
