### ISSUE TITLE
Text must be less than or equal to CHARACTER_LIMIT characters.

### ISSUE THREAD

**Issue by komals1** [tgbot-collection/TeleTweet#2]
Dear developer, I was using teletweet for just few days and it made me so much curious and I stumble upon many things , that it should do more, so here I will just saying what can help me little,

Issue- Error: Text must be less than or equal to CHARACTER_LIMIT characters.
Need- when bot hit the wall of character limit, can this be possible that line break (Enter bottom) command can be used to split the 
            text into threading tweet, only when text limit breached from current tweet.

**Comment by wisdomtooth** [comment]
As a midstep, you could just truncate it.

**Comment by BennyThink** [comment]
Implementation is much more difficult than I expected...

**Comment by wisdomtooth** [comment]
This worked, I think (e.g. [here](https://twitter.com/brigade_health/status/1368189979713757186)).

Personally, I'd prefer it just tweeted the first 280 chars (-24 if it contains a link anywhere) + first 4 photos (or video, if it has one instead).

**Comment by wisdomtooth** [comment]
Is there a setting to turn this off? It's working, but not well. The bot creates a thread alright, but puts the RSS title on one tweet, the image on another, the link on another, and the description on another, instead of it all in one.
