### ISSUE TITLE
[{'code': 185, 'message': 'User is over daily status update limit.'}]

### ISSUE THREAD

**Issue by komals1** [tgbot-collection/TeleTweet#3]
I would start by thanking you for the service, and with that I would like to submit  a few of my thought.
If it is possible to apply, do try to make it happen, whenever you like too, No Rush.

I received a message, when I overused the bot - ** 185 - over User Daily Limit**
it is probably due to Twitter API limit in regard to that if it would be possible to set a time limit on per bot user

Step 1. If a user send more than 5 messages to bot under 5 Minutes for tweeting only
            Then
            6th Next message Should be auto-scheduled to send after 2 minutes.
                       If User send another message before the delivery of 6th message 
                        then it should be auto scheduled for 2 minute again after the delivery of 6th message
             and so on.
Step 2.if the user send a message after 2 minutes than the bot will consider next messages from Step.1 again.

I hope I am able to delivery my thoughts in a mannerful way, with that “Thank You” Again

**Comment by BennyThink** [comment]
Twitter API should provide `retry-after`, maybe I can try to implement delay post according to this header.

**Comment by BennyThink** [comment]
close as not intend to maintenance..
