### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by wisdomtooth** [tgbot-collection/TeleTweet#6]
![image](https://user-images.githubusercontent.com/523901/110225988-5f5faf80-7f36-11eb-85c9-697bfbf67442.png)
It's good having this notification (especially with the link to the tweet!), but after a while, when things are running smoothly, it becomes a nuisance. Is there an option to turn it off?

**Comment by BennyThink** [comment]
I think there might be "send without sound" option. Does this seem reasonable to you?

**Comment by wisdomtooth** [comment]
I meant: with no confirmation msg from the bot.

**Comment by BennyThink** [comment]
I think I can add a custom settings for this, it's not so difficult.

**Comment by BennyThink** [comment]
close as not intend to maintenance..
