### ISSUE TITLE
Error: [{'code': 324, 'message': 'Not valid video'}]

### ISSUE THREAD

**Issue by wisdomtooth** [tgbot-collection/TeleTweet#7]
![image](https://user-images.githubusercontent.com/523901/110226440-07777780-7f3b-11eb-9000-38800eaa7d94.png)
❌ Error: [{'code': 324, 'message': 'Not valid video'}]

The video is 26s long.

**Comment by BennyThink** [comment]
That's strange. I'll take a look soon.

**Comment by BennyThink** [comment]
Unable to reproduce. I'll add a new logic to process this. Maybe you can try it again.

**Comment by wisdomtooth** [comment]
Now this:
![IMG_20210307_143102.jpg](https://user-images.githubusercontent.com/523901/110229018-d191bd80-7f51-11eb-8501-38748ce72662.jpg)

**Comment by BennyThink** [comment]
It's strange.... maybe you can try to convert this video to mp4 and try again?

**Comment by wisdomtooth** [comment]
Yeah, apparently it's something wrong with the video file. It's cut with youtubednbot.

**Comment by BennyThink** [comment]
Did conversion works?

**Comment by wisdomtooth** [comment]
Yeah, definitely a problem with the other bot, not yours. I reenconded the video--it was mp4 already--and this time it worked.
